# config.yml
models:
  - type: main
    engine: openai
    model: gpt-3.5-turbo
    parameters:
      temperature: 0.0      

rails:
  input:
    flows:
      - mask sensitive data on input     # Presidio (no LLM)
      - injection detection              # regex / YARA (no LLM)
  output:
    flows:
      - mask sensitive data on output
  config:
    sensitive_data_detection:            # Presidio tuning
      input:
        entities: [EMAIL_ADDRESS, PERSON]
      output:
        entities: [PERSON]